version: '3.8'
services:
  sadtalker:
    image: paidax/faster-sadtalker-api:0.1.3
    container_name: sadtalker
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./checkpoints:/home/SadTalker/checkpoints
      - ./gfpgan/weights:/home/SadTalker/gfpgan/weights
      - ./results:/home/SadTalker/results
    ports:
      - 10364:10364
    environment:
      - OPENAI_API_KEY={$OPENAI_API_KEY}
    command: uvicorn main:app --reload --port 10364 --host 0.0.0.0