version: '3.8'
services:
  sadtalker:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HTTP_PROXY: ${HTTP_PROXY}
    image: paidax/faster-SadTalker-API:3.0
    container_name: sadtalker
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./checkpoints:/home/SadTalker/checkpoints
      - ./gfpgan/weights:/home/SadTalker/gfpgan/weights
      - ./results:/home/SadTalker/results
    ports:
      - 10364:10364
    environment:
      - TTS_SERVER=${TTS_SERVER}
    command: tail -f /dev/null
