version: '3.8'
services:
  sadtalker:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HTTP_PROXY: ${HTTP_PROXY}
    image: paidax/sadtalker:2.3.2
    container_name: sadtalker
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./checkpoints:/home/SadTalker/checkpoints
      - ./gfpgan/weights:/home/SadTalker/gfpgan/weights
    ports:
      - 10364:10364
    environment:
      - TTS_SERVER=${TTS_SERVER}
    command: uvicorn main:app --host 0.0.0.0 --port 10364
